name: Update Lista HTML

on:
  schedule:
    - cron: '0 6 * * *'   # Ogni giorno alle 6:00 UTC (8:00 italiane d'estate, 7:00 d'inverno)
  workflow_dispatch:       # Permette di avviarlo manualmente da GitHub se vuoi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script to generate lista.html
      run: python generate_lista.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add lista.html
        git commit -m "Aggiornamento automatico lista.html $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "Nessuna modifica"
        git push
